# Generated by Django 5.2.7 on 2025-11-04 03:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['subspecies__species__name', 'subspecies__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('protein', 'Protein Source'), ('medium', 'Medium Source'), ('energy', 'Energy Source'), ('mineral', 'Mineral')], max_length=10)),
                ('crude_protein', models.FloatField(default=0.0, help_text='In %')),
                ('energy', models.FloatField(default=0.0, help_text='kcal/kg')),
                ('calcium', models.FloatField(default=0.0)),
                ('phosphorus', models.FloatField(default=0.0)),
                ('lysine', models.FloatField(default=0.0)),
                ('methionine', models.FloatField(default=0.0)),
                ('salt', models.FloatField(default=0.0)),
                ('crude_fiber', models.FloatField(default=0.0, help_text='In %')),
                ('price_per_kg', models.FloatField(default=0.0, help_text='Cost per kg (₹)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crude_protein', models.FloatField(help_text='In %')),
                ('energy', models.FloatField(help_text='In kcal/kg')),
                ('calcium', models.FloatField(help_text='In %')),
                ('phosphorus', models.FloatField(help_text='In %')),
                ('lysine', models.FloatField(help_text='In %')),
                ('methionine', models.FloatField(help_text='In %')),
                ('salt', models.FloatField(help_text='In %')),
                ('crude_fiber', models.FloatField(default=0.0, help_text='Maximum crude fiber allowed (%)')),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='core.animaltype')),
            ],
            options={
                'ordering': ['animal_type__subspecies__species__name', 'animal_type__subspecies__name', 'animal_type__name', 'name'],
                'unique_together': {('animal_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Subspecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subspecies', to='core.species')),
            ],
            options={
                'ordering': ['species__name', 'name'],
                'unique_together': {('species', 'name')},
            },
        ),
        migrations.AddField(
            model_name='animaltype',
            name='subspecies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_types', to='core.subspecies'),
        ),
        migrations.CreateModel(
            name='Premix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_kg', models.FloatField(default=0.0)),
                ('inclusion_rate', models.FloatField(default=0.25, help_text='% inclusion in feed (e.g. 0.25 for 0.25%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('animal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.animaltype')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.phase')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.species')),
                ('subspecies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subspecies')),
            ],
            options={
                'ordering': ['species__name', 'name'],
                'unique_together': {('species', 'subspecies', 'animal_type', 'phase')},
            },
        ),
        migrations.CreateModel(
            name='IngredientInclusionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_inclusion', models.FloatField(help_text='Max % for this ingredient in the specified taxonomy + phase', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.animaltype')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phase')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.species')),
                ('subspecies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subspecies')),
            ],
            options={
                'ordering': ['species__name', 'subspecies__name', 'animal_type__name', 'phase__name', 'ingredient__name'],
                'unique_together': {('species', 'subspecies', 'animal_type', 'phase', 'ingredient')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='animaltype',
            unique_together={('subspecies', 'name')},
        ),
    ]
