# Generated by Django 4.2.26 on 2025-12-08 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trial', models.BooleanField(default=True, help_text='Is this a trial user?')),
                ('trial_start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When trial started')),
                ('trial_end_date', models.DateTimeField(blank=True, help_text='When trial ends (null = unlimited)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is user account active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTaxonomyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal_type', models.ForeignKey(blank=True, help_text='None = all animal types allowed', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.animaltype')),
                ('phase', models.ForeignKey(blank=True, help_text='None = all phases allowed', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.phase')),
                ('species', models.ForeignKey(blank=True, help_text='None = all species allowed', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.species')),
                ('subspecies', models.ForeignKey(blank=True, help_text='None = all subspecies allowed (if species is set, only within that species)', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subspecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'species__name', 'subspecies__name', 'animal_type__name', 'phase__name'],
                'unique_together': {('user', 'species', 'subspecies', 'animal_type', 'phase')},
            },
        ),
    ]
